volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:

services:

  db:
    image: postgres:13.10
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - foodgram-network

  backend:
    image: vettspace/foodgram_backend:latest
    restart: always
    volumes:
      - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - foodgram-network
    environment:
      - DB_HOST=db

  frontend:
    image: vettspace/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend
    networks:
      - foodgram-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./local-default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    networks:
      - foodgram-network

networks:
  foodgram-network:
    name: foodgram-network