version: '3.8'

services:
  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ./data/:/app/data/
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    volumes:
      - frontend_value:/app/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - frontend_value:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_value: